# Install Musicbrainz

In [1]:
!pip install musicbrainzngs

Requirement already satisfied: musicbrainzngs in c:\users\privat\anaconda3\envs\dst2\lib\site-packages (0.7.1)

In [1]:
import pandas as pd
import musicbrainzngs as mb

### read the cleaned data in

In [6]:
df = pd.read_csv('spotify_cleaned.csv')

In [9]:
df.drop(['Unnamed: 0'], axis=1, inplace=True)

In [10]:
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
854,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
855,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
856,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
857,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

In [11]:
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,bpm,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,125,B,Major,80,89,83,31,0,8,4
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,92,C#,Major,71,61,74,7,0,10,4
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,138,F,Major,51,32,53,17,0,31,6
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,170,A,Major,55,58,72,11,0,11,15
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,144,A,Minor,65,23,80,14,63,11,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,144,A,Major,60,24,39,57,0,8,3
854,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,166,F#,Major,42,7,24,83,1,12,6
855,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,92,C#,Major,80,81,67,4,0,8,6
856,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,97,C#,Major,82,67,77,8,0,12,5
857,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,90,E,Minor,61,32,67,15,0,11,5

### Artists in einer Liste speichern

In [12]:
artist_list = df['artist(s)_name'].tolist()
artist_list

['Latto, Jung Kook',
 'Myke Towers',
 'Olivia Rodrigo',
 'Taylor Swift',
 'Bad Bunny',
 'Dave, Central Cee',
 'Eslabon Armado, Peso Pluma',
 'Quevedo',
 'Gunna',
 'Peso Pluma, Yng Lvcas',
 'Bad Bunny, Grupo Frontera',
 'NewJeans',
 'David Kushner',
 'Harry Styles',
 'SZA',
 'Fifty Fifty',
 'Feid, Young Miko',
 'Jimin',
 'Gabito Ballesteros, Junior H, Peso Pluma',
 'Taylor Swift',
 'Bizarrap, Peso Pluma',
 'The Weeknd, Madonna, Playboi Carti',
 'Fuerza Regida',
 'Rï¿½ï¿½ma, Selena G',
 'Tainy, Bad Bunny',
 'Morgan Wallen',
 'Dua Lipa',
 'Troye Sivan',
 'Peso Pluma, Grupo Frontera',
 'The Weeknd, 21 Savage, Metro Boomin',
 'Taylor Swift',
 'Karol G, Shakira',
 'Yahritza Y Su Esencia, Grupo Frontera',
 'Taylor Swift',
 'Taylor Swift',
 'Fuerza Regida',
 'Junior H, Peso Pluma',
 'Post Malone, Swae Lee',
 'Bebe Rexha, David Guetta',
 'Tyler, The Creator, Kali Uchis',
 'Miley Cyrus',
 'The Weeknd',
 'The Weeknd, Daft Punk',
 'Ariana Grande, The Weeknd',
 'Feid, Myke Towers, Sky Rompiendo',
 'David Guetta, Anne-Marie, Coi Leray',
 'Karol G',
 'Peggy Gou',
 'Tom Odell',
 'The Weeknd',
 'Kali Uchis',
 'Manuel Turizo',
 'dennis, MC Kevin o Chris',
 'PinkPantheress, Ice Spice',
 'Charlie Puth, BTS, Jung Kook',
 'Rauw Alejandro, ROSALï¿½',
 'Ozuna, Feid',
 'Chris Molitor',
 'Taylor Swift',
 'Libianca',
 'Post Malone',
 'Taylor Swift',
 'Rauw Alejandro, Bizarrap',
 'Glass Animals',
 'JVKE',
 'The Neighbourhood',
 'Bizarrap, Quevedo',
 'Coldplay',
 'd4vd',
 'Sam Smith, Kim Petras',
 'Yandel, Feid',
 'Maria Becerra',
 'Vance Joy',
 'Em Beihold, Stephen Sanchez',
 'Mc Livinho, DJ Matt D',
 'Taylor Swift',
 'Justin Bieber, The Kid Laroi',
 'Marshmello, Manuel Turizo',
 'Lewis Capaldi',
 'Chencho Corleone, Bad Bunny',
 'Jain',
 'Ayparia, unxbected',
 'Luke Combs',
 'Doechii',
 'Bad Bunny, Eladio Carrion',
 'Taylor Swift',
 'Jung Kook',
 'J. Cole, Lil Durk',
 'Lana Del Rey',
 'SZA',
 'Lana Del Rey',
 'BTS',
 'Taylor Swift',
 'Future, Metro Boomin, Don Toliver',
 'Post Malone',
 'Eminem',
 'NewJeans',
 'Carin Leon',
 'Dua Lipa, Elton John, Pnau',
 'Ruth B.',
 'Imagine Dragons',
 'Adele',
 'Kendrick Lamar, Jay Rock',
 'Anggi Marito',
 'Jasiel Nuï¿½ï¿½ez, Peso P',
 'Taylor Swift',
 'Tears For Fears',
 'J. Cole',
 'Loreen',
 'Taiu, Milo j',
 'Sebastian Yatra, Manuel Turizo, Beï¿½ï',
 'Taylor Swift',
 'Junior H, Peso Pluma',
 'Calvin Harris, Ellie Goulding',
 'Sabrina Carpenter',
 'Carin Leon, Grupo Frontera',
 'Feid',
 'Ray Dalton, Ryan Lewis, Macklemore',
 'Billie Eilish, Khalid',
 'Rauw Alejandro, Bizarrap',
 '(G)I-DLE',
 'NewJeans',
 'Lana Del Rey',
 'Shakira, Bizarrap',
 'Travis Scott, Young Thug, Metro Boomin',
 'Sachin-Jigar, Shadab Faridi, Altamash Faridi, Amitabh Bhattacharya, Varun Jain',
 'Ed Sheeran',
 'd4vd',
 'Imagine Dragons',
 'Veigh, Bvga Beatz, Supernova Ent, Prod Malax',
 'Mc Pedrinho, DJ 900',
 'Eminem',
 'The Weeknd, Lana Del Rey',
 'Bomba Estï¿½ï¿½reo, Bad B',
 'Keane',
 'New West',
 'Chino Pacas',
 'Natanael Cano',
 'Ana Castela, AgroPlay',
 'Bruno Mars',
 'Big One, FMK, Ke personajes',
 'OneRepublic',
 'Justin Bieber',
 'Chris Brown',
 'Natanael Cano, Peso Pluma',
 'Drake, WizKid, Kyla',
 'Taylor Swift',
 'Miguel',
 'The Police',
 'Lord Huron',
 'Rihanna, Calvin Harris',
 'Alec Benjamin',
 'A$AP Rocky, Metro Boomin, Roisee',
 'Arctic Monkeys',
 'Imagine Dragons',
 'YOASOBI',
 'The Weeknd',
 'Taylor Swift',
 'Arctic Monkeys',
 'Ed Sheeran',
 'One Direction',
 'Radiohead',
 'James Arthur',
 'Cigarettes After Sex',
 'Shubh',
 'Frank Ocean',
 'Bruno Mars',
 'Hozier',
 'Fuerza Regida, Grupo Frontera',
 'Taylor Swift',
 'Bad Bunny',
 'Taylor Swift',
 'Hotel Ugly',
 'Plan B',
 'Feid, Mora, Saiko, Quevedo',
 'NewJeans',
 'a-ha',
 'Swae Lee, Lil Wayne, Offset, Metro Boomin',
 'Kodak Black, NLE Choppa, Muni Long, JVKE, Jimin',
 'Shakira',
 'Natanael Cano, Gabito Ballesteros, Peso Pluma',
 'Arijit Singh, Sachin-Jigar, Amitabha Bhattacharya',
 'Stray Kids',
 'Taylor Swift',
 'Becky G, Peso Pluma',
 'Metro Boomin, Coi Leray',
 'Kaliii, Kaliii',
 'Junior H, Eden Muï¿½ï',
 'Abhijay Sharma, Riar Saab',
 'Semicenk, Doï¿½ï¿½u ',
 'JISOO',
 'Future, Lil Uzi Vert, Metro Boomin',
 'Ed Sheeran',
 'RAYE, 070 Shake',
 'Arcangel, Bad Bunny',
 'Taylor Swift, Ice Spice',
 'Future, Chris Brown, Metro Boomin',
 'BLESSD, Peso Pluma',
 'Feid',
 'Fuerza Regida, Natanael Cano',
 'Lana Del Rey, Taylor Swift',
 'Coi Leray',
 'ENHYPEN',
 'Lil Durk, Morgan Wallen',
 'Feid',
 'James Blake, Metro Boomin',
 'Israel & Rodolffo, Mari Fernandez',
 'Steve Lacy',
 'Beyoncï¿',
 'Halsey, Suga',
 'Nicky Jam, Feid',
 'Sean Paul, Feid',
 'Drake',
 'Kendrick Lamar, Beyoncï¿',
 'Taylor Swift',
 'WizKid, Toian, Metro Boomin, Don Toliver, Beam',
 'Bad Bunny',
 'Simone Mendes',
 'Tini',
 'Lil Uzi Vert',
 'Sia',
 'Stephen Sanchez',
 'Drake, 21 Savage',
 'Adele',
 'MC Caverinha, KayBlack',
 'Offset, JID',
 'Zï¿½ï¿½ Neto & Crist',
 'Eminem',
 'Migrantes, LiL CaKe, Nico Valdi',
 'Tory Lanez',
 'Joji',
 'Mambo Kingz, DJ Luian, Anuel Aa',
 'Ed Sheeran',
 'Nile Rodgers, LE SSERAFIM',
 'Agust D',
 'Rich The Kid, Matuï¿',
 'Labrinth',
 'Karol G, Romeo Santos',
 'Lizzy McAlpine',
 'Fifty Fifty',
 'IVE',
 'sped up 8282',
 'Cartel De Santa, La Kelly',
 'SEVENTEEN',
 'NLE Choppa',
 'The Weeknd, Future',
 'Taylor Swift',
 'Karol G',
 'Nicki Minaj, Ice Spice',
 'Grupo Marca Registrada, Grupo Frontera',
 'Ed Sheeran',
 'Fuerza Regida, Peso Pluma',
 'TAEYANG, Lisa',
 'Raim Laode',
 'ROSALï¿½',
 'Meghan Trainor',
 'sped up nightcore, ARIZONATEARS, Lil Uzi Vert',
 'Quevedo',
 'TV Girl',
 'INTERWORLD',
 'Quevedo, Jhayco',
 'El Chachito, Junior H',
 'The Weeknd, Gesaffelstein',
 'RM, Colde',
 'Nengo Flow, Bad Bunny',
 'The Weeknd',
 'Jimin',
 'Jasiel Nuï¿½ï¿½ez, Peso P',
 'Nicky Youre, Dazy',
 'Eminem',
 'Eminem, Dina Rae',
 'Mambo Kingz, DJ Luian, Anuel Aa',
 'IU, Agust D',
 'Feid',
 'Arcangel, Bizarrap',
 'Tyler, The Creator',
 'Tiï¿½ï¿½sto, Tate M',
 'Tyler, The Creator',
 'NF',
 'Yng Lvcas',
 'Kanii, PR1ISVX',
 'Harry Styles',
 'Marï¿½ï¿½lia Mendo',
 'Zach Bryan',
 'Melanie Martinez',
 'Fuerza Regida, Chino Pacas',
 'Mae Stephens',
 'Morgan Wallen',
 'Feid, Mora',
 'Kenia OS',
 'Kordhell',
 'Coolio, L.V.',
 'Karol G, Ovy On The Drums',
 'The Walters',
 'Steve Lacy',
 'James Arthur',
 'Mac DeMarco',
 'Jack Black',
 'Duki, NICKI NICOLE, Cris Mj, Standly, Stars Music Chile',
 'Brray, Rauw Alejandro, Lyanno',
 'Linkin Park',
 'j-hope, J. Cole',
 'Morgan Wallen',
 'Robin Schulz, Oliver Tree',
 'Morgan Wallen',
 'Morgan Wallen',
 'Don Toliver, Future, Justin Bieber',
 'Morgan Wallen',
 'Niall Horan',
 'Central Cee',
 'Mahalini',
 'Morgan Wallen',
 'Arijit Singh, Sachin-Jigar',
 'ThxSoMch',
 'Myke Towers, Quevedo',
 'Morgan Wallen, Eric Church',
 'Nicki Minaj',
 'Kaifi Khalil',
 'SZA',
 'Karol G, Quevedo',
 'NewJeans',
 'Lady Gaga',
 'Morgan Wallen',
 'Quevedo',
 'Morgan Wallen',
 'Linkin Park',
 'Leo Santana',
 'Treyce',
 'Post Malone, Doja Cat',
 'Bad Bunny',
 'MC Xenon, Os Gemeos da Putaria',
 'Imagine Dragons, League of Legends, JID, Arcane',
 'XXXTENTACION',
 'Israel & Rodolffo, Ana Castela',
 'J Balvin, Bad Bunny',
 'Yuridia, Angela Aguilar',
 'The Kid Laroi',
 'The Weeknd',
 'Lizzo',
 'Fujii Kaze',
 'Wisin & Yandel, ROSALï¿½',
 'King',
 'Bad Bunny',
 'Coldplay, BTS',
 'ROSALï¿½',
 'P!nk',
 'LE SSERAFIM',
 'PinkPantheress',
 'SZA',
 'Rihanna',
 'Lil Nas X',
 'Beach Weather',
 'Halsey, BTS',
 'Baby Tate',
 'Rï¿½ï',
 'Arijit Singh, Vishal Dadlani, Sukriti Kakar, Vishal-Shekhar, Shekhar Ravjiani, Kumaar',
 'RAYE, 070 Shake',
 'Shakira, Rauw Alejandro',
 'Steve Aoki, Tini, La Joaqui',
 'Billie Eilish',
 'Sam Smith',
 'Conan Gray',
 'Vishal-Shekhar, Shilpa Rao, Caralisa Monteiro, Kumaar, Vishal Dadlani, Shekhar Ravjiani',
 'Calvin Harris, Dua Lipa',
 'TOMORROW X TOGETHER',
 'Drake, Future, Tems',
 'Dua Lipa',
 'Mr.Kitty',
 'Jack Harlow, Lil Nas X',
 'Elley Duhï¿',
 'Seafret',
 'DJ Escobar, MC MENOR SG, MC MENOR HR',
 'Dean Lewis',
 'SZA',
 'Joji',
 'Central Cee',
 'Bellakath',
 'Skrillex, Flowdan, Fred again..',
 'Travis Scott, 21 Savage, Metro Boomin',
 'Bad Bunny',
 'Nicki Minaj',
 'Kate Bush',
 'Aerosmith',
 'Freddie Dredd',
 'Lost Frequencies, Calum Scott',
 'Twisted, Oliver Tree',
 'Ed Sheeran',
 'Kenshi Yonezu',
 'Omar Apollo',
 'SZA',
 'Dua Lipa, DaBaby',
 'Doja Cat',
 'Hotel Ugly',
 'James Hype, Miggy Dela Rosa',
 'Taylor Swift',
 'Styrx, utku INC, Thezth',
 'Maroon 5, Wiz Khalifa',
 'Mariah Carey',
 'Wham!',
 'Brenda Lee',
 'Bobby Helms',
 'Michael Bublï¿',
 'Ariana Grande',
 'Andy Williams',
 'Dean Martin',
 'Sia',
 'Kelly Clarkson',
 'Josï¿½ï¿½ Felic',
 'Michael Bublï¿',
 'Justin Bieber',
 'The Ronettes',
 'SZA',
 'SZA',
 'John Lennon, The Harlem Community Choir, The Plastic Ono Band, Yoko Ono',
 'SZA, Don Toliver',
 'Nat King Cole',
 'Paul McCartney',
 'SZA, Phoebe Bridgers',
 "Shakin' Stevens",
 'Frank Sinatra, B. Swanson Quartet',
 'SZA',
 'SZA, Travis Scott',
 'Bing Crosby, John Scott Trotter & His Orchestra, Ken Darby Singers',
 'Chris Rea',
 'Darlene Love',
 'SZA',
 'SZA',
 'SZA',
 'Perry Como, The Fontane Sisters, Mitchell Ayres & His Orchestra',
 'Mabel Matiz, Mert Demir',
 'RM',
 'SZA',
 'Travis Scott, Metro Boomin',
 'ThxSoMch',
 'Nat King Cole',
 'SZA',
 'SZA',
 'Taylor Swift, Lana Del Rey',
 'Taylor Swift',
 'Dj LK da Escï¿½ï¿½cia, Tchakabum, mc jhenny, M',
 'Taylor Swift',
 'Bad Bunny, Jhay Cortez',
 'Gwen Stefani, Blake Shelton',
 'Chencho Corleone, Rauw Alejandro',
 'SZA',
 'Bad Bunny, Rauw Alejandro',
 'Chuck Berry',
 'Frank Sinatra',
 'SZA',
 'John Legend, Metro Boomin',
 'Maldy, Karol G',
 'Gayle',
 'The Weeknd',
 'The Weeknd',
 'Lauren Spencer Smith, Lauren Spencer Smith, Lauren Spencer Smith',
 'Cherish, ACRAZE',
 'Farruko',
 'The Weeknd',
 'The Weeknd',
 'Jaymes Young',
 'The Weeknd',
 'Olivia Rodrigo',
 'The Weeknd, Tyler, The Creator',
 'The Weeknd',
 'SZA, Doja Cat',
 'The Weeknd, Lil Wayne',
 'Doja Cat',
 'Lil Nas X',
 'Ckay',
 'The Weeknd',
 'Jessica Darrow',
 'The Weeknd',
 'Lil Nas X',
 'The Weeknd, Post Malone',
 'Mï¿½ï¿½ne',
 'Aitana, zzoilo',
 'Julieta Venegas, Bad Bunny, Tainy',
 'Lisa',
 'Tiï¿½ï¿½sto, Ava',
 'Juan Cruz Toledo, Huilen Toledo',
 'BoyWithUke',
 'Olivia Rodrigo',
 'Xamï¿½ï¿½, Gustah, Neo B',
 'The Weeknd',
 'Adele',
 'Lit Killah, Maria Becerra, Tiago pzk, NICKI NICOLE',
 'The Weeknd',
 'Emmy Meli',
 'Justin Quiles, Lenny Tavï¿½ï¿½rez, BL',
 'Shawn Mendes',
 'The Neighbourhood',
 'Kodak Black',
 'Aventura, Bad Bunny',
 'Rauw Alejandro',
 "Ckay, AX'EL, Dj Yo!",
 'Bruno Mars, Anderson .Paak, Silk Sonic',
 'THE ANXIETY, Willow, Tyler Cole',
 'Sebastian Yatra',
 'Bad Bunny, Jhay Cortez',
 'Bizarrap, Tiago pzk',
 'Stromae',
 'Chris Brown, Rvssian, Rauw Alejandro',
 'Kali Uchis, Amaarae, Moliy',
 'BTS',
 'Young Thug, Future, Gunna',
 'Doja Cat, The Weeknd',
 'Olivia Rodrigo',
 'BTS',
 'Jnr Choi',
 'The Weeknd, Gesaffelstein',
 'Trueno, Tiago pzk',
 'Sech, Bad Bunny, Mora',
 'Bruno Mars, Anderson .Paak, Silk Sonic',
 'Drake, Project Pat, 21 Savage',
 'Tiï¿½ï¿½sto, Kar',
 'Edison Lighthouse',
 'Olga Merediz, Stephanie Beatriz, Encanto - Cast',
 'The Weeknd',
 'Surf Curse',
 'Jason Derulo',
 'The Neighbourhood',
 '21 Savage, Gunna',
 'IVE',
 '24kgoldn, Iann Dior',
 'Stephanie Beatriz, Diane Guerrero',
 'David Kushner',
 'Olivia Rodrigo',
 'Kanye West',
 'Doja Cat',
 'Lewis Capaldi',
 'Playboi Carti',
 'Adele',
 'Maluma',
 'Ed Sheeran, Fireboy DML',
 'Olivia Rodrigo',
 'Prezioso, Gabry Ponte, LUM!X',
 'Tiï¿½ï¿',
 'Mï¿½ï¿½ne',
 'Marï¿½ï¿½lia Mendonï¿½ï¿½a, George Henrique &',
 'TWICE',
 'Sean Paul, Dua Lipa',
 'Charli XCX, Jax Jones, Joel Corry, Saweetie',
 'SALES',
 'Sleepy hallow',
 'Billie Eilish',
 'Masked Wolf',
 'Anuel Aa, Jhay Cortez',
 'NIKI',
 'Bruno Mars',
 'Tate McRae',
 'Avicii',
 'The Weeknd',
 'Drake, Future, Young Thug',
 'Rauw Alejandro',
 'Imagine Dragons, League of Legends, Arcane',
 'Tones and I',
 'Juice WRLD',
 'J Balvin, Maria Becerra',
 'John Legend',
 'Nirvana',
 'Duncan Laurence',
 'Drake, Travis Scott',
 'Tini, L-Gante',
 'SiM',
 'Kendrick Lamar, Baby Keem',
 'The Killers',
 'ENHYPEN',
 'J Balvin, Nio Garcia, Bad Bunny',
 'Doja Cat',
 'Lady Gaga, Bradley Cooper',
 'ENHYPEN',
 'Marshmello, Jonas Brothers',
 'BTS',
 'Riton, Nightcrawlers, Mufasa & Hypeman, Dopamine',
 'Polo G',
 'Eminem, Nate Dogg',
 'Maroon 5',
 'Arcangel, De La Ghetto, Justin Quiles, Lenny Tavï¿½ï¿½rez, Sech, Dalex, Dimelo Flow, Rich Music',
 'Gunna, Lil Baby',
 'Marï¿½ï¿½lia Mendonï¿½ï¿½a, Maiara &',
 'Tini, Maria Becerra',
 'Anuel Aa, Myke Towers, Jhay Cortez',
 'Karol G, Becky G',
 'Dr. Dre, Snoop Dogg',
 'Jung Kook',
 'Dove Cameron',
 'Dr. Dre, Snoop Dogg',
 'Charlie Puth',
 'Kanye West, Alicia Keys, Fivio Foreign',
 'Mahmood, Blanco',
 'Frank Ocean',
 '50 Cent',
 'Tate McRae',
 'Yung Lean',
 'Labrinth, Zendaya',
 'The Rare Occasions',
 'Labrinth',
 'Intense, AP Dhillon, Gurinder Gill',
 'Juice WRLD',
 'Quevedo, La Pantera, Juseph, Cruz Cafunï¿½ï¿½, Bï¿½ï¿½jo, Abhir Hathi',
 'Dr. Dre, 2Pac, Roger',
 'Eminem, Dr. Dre',
 'Luude, Colin Hay',
 'Ryan Castro',
 'Kendrick Lamar',
 'Eminem, Dido',
 'GODZZ__-, Zakaria',
 'Chase Atlantic',
 'Em Beihold',
 'Mainstreet, Chefin',
 'Alvaro Diaz, Rauw Alejandro',
 'Nicki Minaj, Lil Baby',
 'Future',
 'Zï¿½ï¿½ Fe',
 'Muni Long',
 'Vundabar',
 'Ed Sheeran',
 'Labrinth',
 'V',
 'Labrinth',
 'Nicki Minaj, Lil Baby',
 'Labrinth',
 'Eminem, Dr. Dre',
 'Shawn Mendes, Camila Cabello',
 'Tyler, The Creator',
 'Harry Styles',
 'Daddy Yankee, Bad Bunny',
 'Nirvana',
 'Dua Lipa, Megan Thee Stallion',
 'Camila Cabello, Ed Sheeran',
 'Cris Mj',
 'Anitta',
 'Dave',
 'Tulus',
 'Mc Pedrinho, Pedro Sampaio',
 'Zion & Lennox',
 'Residente, Bizarrap',
 'Ryan Castro',
 'Jack Harlow',
 'Eden Muï¿½ï',
 'Christian Nodal',
 'Tyga, Doja Cat',
 'JVKE',
 'Bad Bunny',
 'XXXTENTACION',
 'Dua Lipa',
 'Avicii',
 'Olivia Rodrigo',
 'YEAT',
 'C. Tangana',
 'The Chainsmokers, Coldplay',
 'The Chainsmokers, Halsey',
 'NMIXX',
 'AnnenMayKantereit, Giant Rooks',
 'Jack Harlow',
 'Danny Ocean',
 'Daddy Yankee, Bad Bunny',
 'Shawn Mendes',
 'Lil Tjay',
 'Willow',
 'IVE',
 'Feid, Alejo, Robi',
 'Paulo Londra',
 'Demi Lovato',
 'Camila Cabello, Willow',
 'Troye Sivan',
 'Matuï¿½ï¿½, Wiu, ',
 'De La Ghetto, Duki, Quevedo',
 'Lil Baby',
 'Charlie Puth',
 'Yahritza Y Su Esencia',
 'Daddy Yankee',
 'Luï¿½ï¿½sa Sonza, MC Frog, Dj Gabriel do Borel, Davi K',
 'Harry Styles',
 'Ed Sheeran, J Balvin',
 'teto',
 'Stray Kids',
 'Shawn Mendes',
 'Blackbear, BoyWithUke',
 'Harry Styles',
 'Pharrell Williams, Nile Rodgers, Daft Punk',
 'Doja Cat',
 "Jordan Fisher, Josh Levi, Finneas O'Connell, 4*TOWN (From Disney and Pixarï¿½ï¿½ï¿½s Turning Red), Topher Ngo, Grayson Vill",
 'BIGBANG',
 'Ed Sheeran',
 'Justin Bieber',
 'Kendrick Lamar',
 'Lizzo',
 'Kendrick Lamar, Blxst, Amanda Reifer',
 'Bad Bunny',
 'Kendrick Lamar',
 'Kendrick Lamar, Sampha',
 'Kendrick Lamar',
 'Bad Bunny',
 'Kendrick Lamar, Kodak Black',
 'Tony Dize, Bad Bunny',
 'Kendrick Lamar',
 'Buscabulla, Bad Bunny',
 'Bad Bunny',
 'Kendrick Lamar, Taylour Paige',
 'Kendrick Lamar, Sam Dew, Baby Keem',
 'Bad Bunny',
 'Bad Bunny, The Marï¿½ï',
 'Kendrick Lamar',
 'Bad Bunny',
 'Kendrick Lamar, Ghostface Killah, Summer Walker',
 'Bad Bunny',
 'Polima WestCoast, Pailita',
 'Bad Bunny',
 'Bad Bunny',
 'Bad Bunny, Tainy',
 'Jack Harlow',
 'Bad Bunny',
 'Panic! At The Disco',
 'Kendrick Lamar, Tanna Leone',
 'PSY, Suga',
 'Benson Boone',
 'Kendrick Lamar',
 'Mï¿½ï¿½ne',
 'KALUSH',
 'The Kid Laroi',
 'Kendrick Lamar',
 'Kendrick Lamar',
 'Future',
 'Kendrick Lamar',
 'Luciano',
 'Kendrick Lamar',
 'Shae Gill, Ali Sethi',
 'Kendrick Lamar, Beth Gibbons',
 'Sech, Mora',
 'MNEK, Jax Jones',
 'Ugly Dray, Tesla Jnr',
 'Justin Bieber, Don Toliver',
 'Jessi',
 'Chanel',
 'LE SSERAFIM',
 'Leah Kate',
 'Sam Ryder',
 'HA SUNG WOON, Jimin',
 'The Goo Goo Dolls',
 'Kendrick Lamar',
 'Kevin Kaarl',
 'Taylor Swift',
 'Suki Waterhouse',
 'Lauren Spencer Smith',
 'BTS',
 'BTS',
 'Harry Styles',
 'Harry Styles',
 'BTS',
 'Doja Cat',
 'Pharrell Williams, Tyler, The Creator, 21 Savage',
 'Calvin Harris, Dua Lipa, Young Thug',
 'BTS',
 'Harry Styles',
 'Nengo Flow, Anuel Aa, Chris Jedi, Chencho Corleone',
 'Kanye West, XXXTENTACION',
 'Musical Youth',
 'Bizarrap, Villano Antillano',
 'Harry Styles',
 'Harry Styles',
 'Halsey',
 'BYOR, Imanbek',
 'Harry Styles',
 'Harry Styles',
 'Sleepy hallow, 347aidan',
 'Paloma Faith',
 'Lady Gaga',
 'Harry Styles',
 'Ozuna, Tiago pzk',
 'Childish Gambino',
 'David Guetta, Ella Henderson, Becky Hill',
 'Joji',
 'Duki',
 'Sidhu Moose Wala',
 'Victor Cibrian',
 'Metallica',
 'Beyoncï¿',
 'De La Ghetto, Feid, Polima WestCoast, Paloma Mami, Pailita',
 'Drake',
 'Yung Gravy',
 'Lasso',
 'Nayeon',
 'Schï¿½ï¿½rze, DJ R',
 'j-hope',
 "Guns N' Roses",
 'Burna Boy',
 'Drake',
 'Kanye West, Lil Durk, Cardi B',
 'L7nnon, DJ Biel do Furduncinho, Bianca',
 'Anitta, Tini, Becky G',
 'Nessa Barrett',
 'LF System',
 'Mc Vitin Da Igrejinha, MC Tairon, DJ Win',
 'Rels B',
 'Drake, DJ Khaled, Lil Baby',
 'Feid',
 'Duki',
 'Beyoncï¿',
 'Ghost',
 'NewJeans',
 'Rex Orange County',
 'Sofia Carson',
 'Grupo Marca Registrada, Junior H',
 'Kanye West',
 'Calvin Harris, Halsey, Pharrell Williams, Justin Timberlake',
 'Luis R Conriquez, La Adictiva',
 'David Guetta, Shakira, Black Eyed Peas',
 'Melody, Ana Castela, Dj Chris No Beat',
 'Lewis Capaldi',
 'Kanye West',
 'TWICE',
 'Armani White',
 'Feid',
 'Oxlade',
 'Feid',
 'Steve Lacy',
 'Coldplay',
 'Coldplay',
 'YEAT',
 'Yandel, Feid',
 'PnB Rock',
 'Ovy On The Drums, Quevedo',
 'Feid',
 'Lil Yachty',
 'Mï¿½ï¿½ne',
 'Marshmello, Juice WRLD',
 'Fran C, Polima WestCoast, Nickoog Clk, Pablito Pesadilla',
 '(G)I-DLE',
 'Southstar',
 'girl in red',
 'Lizzo',
 'Ed Sheeran',
 'BLACKPINK',
 'Rosa Walton, Hallie Coggins',
 'Lil Baby',
 'Luciano, Aitch, Bï¿½',
 'MC Ryan SP, Love Funk, Mc Paiva ZS',
 'Drake, 21 Savage',
 'Drake, Travis Scott, 21 Savage',
 'Taylor Swift',
 'Taylor Swift',
 'Drake, 21 Savage',
 'Taylor Swift',
 'Drake, 21 Savage',
 'Drake, 21 Savage',
 'Taylor Swift',
 'Ludwig Goransson, Foudeqush',
 'Drake, 21 Savage',
 'Jin',
 'Drake',
 'Drake, 21 Savage',
 'Taylor Swift',
 'Selena Gomez',
 'Taylor Swift',
 'Feid, Paulo Londra',
 'Feid, Sech, Jhayco',
 'Burna Boy']

### Funktion erstellen um das Herkunftsland des Künstlers mithilfe von musicbrainz zu bekommen

In [13]:
def find_artist_country(artist_name):

    mb.set_useragent("Artist_Country", "1.0", contact="l-brahner@t-online.de")
    try:
        result = mb.search_artists(artist=artist_name, limit=1)
        if result['artist-list']:
            artist = result['artist-list'][0]
            country = artist['area']['name']

            return country
        else:
            return "Artist not found"
    except Exception as e:
        return f"Error: {e}"

### Funktion anwenden

In [14]:
artist_country_list = []

for artist in artist_list:
    artist_country_list.append(find_artist_country(artist))

In [15]:
df['artist_country'] = artist_country_list

In [16]:
df

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,artist_country
0,Seven (feat. Latto) (Explicit Ver.),"Latto, Jung Kook",2,2023,7,14,553,147,141381703,43,...,B,Major,80,89,83,31,0,8,4,South Korea
1,LALA,Myke Towers,1,2023,3,23,1474,48,133716286,48,...,C#,Major,71,61,74,7,0,10,4,Puerto Rico
2,vampire,Olivia Rodrigo,1,2023,6,30,1397,113,140003974,94,...,F,Major,51,32,53,17,0,31,6,United States
3,Cruel Summer,Taylor Swift,1,2019,8,23,7858,100,800840817,116,...,A,Major,55,58,72,11,0,11,15,United States
4,WHERE SHE GOES,Bad Bunny,1,2023,5,18,3133,50,303236322,84,...,A,Minor,65,23,80,14,63,11,6,Puerto Rico
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
853,My Mind & Me,Selena Gomez,1,2022,11,3,953,0,91473363,61,...,A,Major,60,24,39,57,0,8,3,United States
854,Bigger Than The Whole Sky,Taylor Swift,1,2022,10,21,1180,0,121871870,4,...,F#,Major,42,7,24,83,1,12,6,United States
855,A Veces (feat. Feid),"Feid, Paulo Londra",2,2022,11,3,573,0,73513683,2,...,C#,Major,80,81,67,4,0,8,6,Argentina
856,En La De Ella,"Feid, Sech, Jhayco",3,2022,10,20,1320,0,133895612,29,...,C#,Major,82,67,77,8,0,12,5,Colombia
857,Alone,Burna Boy,1,2022,11,4,782,2,96007391,27,...,E,Minor,61,32,67,15,0,11,5,Nigeria

In [17]:
df[df['artist_country'] == 'Artist not found']

,track_name,artist(s)_name,artist_count,released_year,released_month,released_day,in_spotify_playlists,in_spotify_charts,streams,in_apple_playlists,...,key,mode,danceability_%,valence_%,energy_%,acousticness_%,instrumentalness_%,liveness_%,speechiness_%,artist_country
81,MONTAGEM - FR PUNK,"Ayparia, unxbected",2,2012,6,20,641,50,58054811,1,...,A,Major,63,84,82,70,8,9,7,Artist not found
208,CUFF IT,Beyoncï¿,1,2022,7,29,7842,10,595900742,215,...,G,Major,78,64,69,4,0,7,14,Artist not found
310,Sial,Mahalini,1,2023,1,23,134,4,166570053,4,...,D,Major,56,20,43,89,0,12,4,Artist not found
777,BREAK MY SOUL,Beyoncï¿,1,2022,6,21,9724,0,354614964,222,...,C#,Minor,70,87,88,4,0,26,8,Artist not found
798,ALIEN SUPERSTAR,Beyoncï¿,1,2022,7,29,2688,0,171788484,39,...,A#,Minor,55,46,64,0,0,17,10,Artist not found

### Spalten droppen mit artist not found

In [18]:

df = df[df['artist_country'] != 'Artist not found']

### spalten droppen mit Error

In [19]:
df = df[~df['artist_country'].str.contains('Error')]

In [21]:
df.to_csv('spotify_angereichert_cleaned.csv')